blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('blog/', views.BlogList.as_view(), name='bloglist'),
    path('blog/<int:pk>', views.BlogDetail.as_view(), name='blogdetail'),
    path('blog/blogtype/<int:pk>', views.BlogTypeList.as_view(), name='blogtypelist')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from django.conf import settings
from django.contrib import auth
from django.contrib.auth.models import User


# Create your models here.

class BlogType(models.Model):
    type_name = models.CharField('博客类型', max_length=20)

    def __str__(self):
        return self.type_name

    class Meta:
        ordering = ('pk')


class Blog(models.Model):
    blog_type = models.ForeignKey(to=BlogType, on_delete=models.CASCADE, related_name='blogs', default=1)
    title = models.CharField('标题', max_length=50)
    content = models.TextField('内容')
    author = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='blogs',
                               verbose_name='作者', default=1)
    create_time = models.DateTimeField('发布时间', auto_now_add=True)
    last_update_time = models.DateTimeField('修改时间', auto_now=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView

from .models import Blog, BlogType


# Create your views here.

class BlogList(ListView):
    model = Blog
    ordering = '-create_time'
    template_name = 'blog/blog_list.html'
    context_object_name = 'blog_list'


class BlogDetail(DetailView):
    model = Blog
    template_name = 'blog/blog_detail.html'


class BlogTypeList(ListView):
    model = Blog
    ordering = '-create_time'
    template_name = 'blog/blog_type_list.html'
    context_object_name = 'blog_type_list'

    def get_queryset(self):
        self.blogtype = get_object_or_404(BlogType, pk=self.kwargs.get('pk'))
        queryset = self.blogtype.blogs.all().order_by('-create_time')# Blog.objects.filter(blog_type=blogtype)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['blogtype'] = self.blogtype
        return context

blog/templates/blog/blog_detail.html
{% extends 'base.html' %}

{% block title %}{{ blog.title }} - {{ block.super }}{% endblock %}

{% block body %}
    <p>{{ blog.title }} - {{ blog.author }} ({{ blog.create_time }})</p>
    <p>{{ blog.content }}</p>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'base.html' %}

{% block title %}列表 - {{ block.super }}{% endblock %}

{% block body %}
    {% for blog in blog_list %}
        <p><a href="{% url 'blog:blogdetail' blog.pk %}">{{ blog.title }}</a>
            <a href="{% url 'blog:blogtypelist' blog.blog_type.id %}">{{ blog.blog_type }}</a>
        </p>
        <p>{{ blog.author }}({{ blog.create_time }})</p>
        {{ blog.content | truncatechars:30 }}
    {% endfor %}
{% endblock %}

blog/templates/blog/blog_type_list.html
{% extends 'base.html' %}

{% block title %}{{ blogtype.type_name }} - {{ block.super }}{% endblock %}

{% block body %}
    {% for blog in blog_type_list %}
        <p><a href="{% url 'blog:blogdetail' blog.pk %}">{{ blog.title }}</a>
            {#            <a href="{% url 'blog:blogtypelist' blog.blog_type.id %}">{{ blog.blog_type }}</a>#}
            {{ blog.blog_type }}
        </p>
        <p>{{ blog.author }}({{ blog.create_time }})</p>
        {{ blog.content | truncatechars:30 }}
    {% endfor %}
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}博客{% endblock %}</title>
    <link href="{% static 'css/bootstrap.min.cdd' %}" rel="stylesheet">
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>